#!/bin/sh

source ./functions/deploy_start.sh

export target=$1

deploy_start

# ----------------------------------------------------
#
# 下面的脚本会在远程路由器之上执行, 请根据所需，酌情修改。
#
# ---------------------------------------------------

# 初始化 entware. 建议手动执行。
# entware-setup.sh; opkg update && opkg upgrade

#  可选的安装一些有用的工具，编辑器, 离线下载等等.
opkg install nginx aria2

# ----------------------------------------------------
#
# 下面执行一些脚本检查与替换。
#
# ---------------------------------------------------

# 如需替换默认密码为新密码, 请取消注释下面这一行。
# 这个密码当你部署 YAAW 时，需要指定。http://token:你的密码@192.168.1.1:6800/jsonrpc
# replace_string Passw0rd '你的密码' /opt/etc/aria2.conf

aria2c --check-certificate=false https://github.com/binux/yaaw/archive/master.zip
unzip yaaw-master.zip
cp yaaw-master/* /opt/share/nginx/html -a
rm yaaw-master.zip yaaw-master/ -rf

/opt/etc/init.d/S80nginx restart
/opt/etc/init.d/S81aria2 restart

add_service services-start 'cru a run-services "*/1 * * * *" "/jffs/scripts/services-start"'
